/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xhsqygawsgsnpfwemczi"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhoc3F5Z2F3c2dzbnBmd2VtY3ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE3NzM5OTAsImV4cCI6MjA5NzM0OTk5MH0.gV-jkhA5eVttiuiZYPB-1NaQL1oKmIFBHDmJu4VSrPQ"